### ISSUE TITLE
Error undeploying application for target host in cluster

### ISSUE THREAD

**Issue by jcdesrochers** [sapia-oss/corus#1]
Corus version: 4.4.3

Error executing a corus script.

The command executed in the script is the following:
undeploy all -cluster ${cluster.targets}

The output of the script execution:
[~]$ coruscli -s deploy/deploy_targeted.txt -cluster.targets chelgpsvmstr015:8100
----- TARGETS: chelgpsvmstr015:8100 -----
----- Step 1: Killing application processes
Waiting for process termination, please stand by...
Process(es) terminated.
----- Step 2: Undeploying applications
java.lang.NullPointerException
at org.sapia.corus.client.cli.command.CorusCliCommand.displayProgress(CorusCliCommand.java:167)
at org.sapia.corus.client.cli.command.Undeploy.doUndeployDist(Undeploy.java:75)
at org.sapia.corus.client.cli.command.Undeploy.doExecute(Undeploy.java:51)
at org.sapia.corus.client.cli.command.CorusCliCommand.execute(CorusCliCommand.java:124)
at org.sapia.corus.client.cli.Interpreter.eval(Interpreter.java:184)
at org.sapia.corus.client.cli.Interpreter.interpret(Interpreter.java:138)
at org.sapia.corus.client.cli.CorusCli.main(CorusCli.java:202)

**Comment by jcdesrochers** [comment]
Assign to Yanick for investigation

**Comment by yduchesne** [comment]
It is not required to specify the ${cluster.targets} variable in the -cluster switch, for scripts that are invoked through the ripple command. Occurrences of the -cluster switch present in such scripts are automatically hijacked by the ripple command to include the right cluster targets.

Therefore, when using ${cluster.targets} in such scripts, the value for that variable is not resolved anymore, resulting in an error.
