### ISSUE TITLE
Unable to start process when property has no value

### ISSUE THREAD

**Issue by jcdesrochers** [sapia-oss/corus#2]
On corus 4.5, define a property with the command 'conf add -p emptyArg=""' and start a process.

We get the following starting the process:

2015.01.22@06:34:13:755 ERROR[org.sapia.corus.taskmanager.CorusTaskManagerImpl]: ExecTask >> Problem occurred executing task java.lang.reflect.InvocationTargetException
        at org.sapia.corus.taskmanager.core.FutureResult.completed(FutureResult.java:47)
        at org.sapia.corus.taskmanager.core.TaskManagerImpl$2.run(TaskManagerImpl.java:107)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:646)
        at org.sapia.corus.processor.task.PerformExecProcessTask.getProcessProps(PerformExecProcessTask.java:219)
        at org.sapia.corus.processor.task.PerformExecProcessTask.execute(PerformExecProcessTask.java:78)
        at org.sapia.corus.processor.task.PerformExecProcessTask.execute(PerformExecProcessTask.java:45)
        at org.sapia.corus.taskmanager.core.TaskManagerImpl$2.run(TaskManagerImpl.java:101)
        ... 3 more

**Comment by jcdesrochers** [comment]
Reproduced the issue with unit test and fixed it.
