### ISSUE TITLE
Got sporadic java.net.SocketException: Socket closed error when getting progress from Corus in the CLI

### ISSUE THREAD

**Issue by yduchesne** [sapia-oss/corus#20]
The error below happens while the CLI is attempting to fetch progress messages from Corus, upon deployment. It is occasional. 

CAUSED BY:  java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy14.hasNext(Unknown Source)
	at org.sapia.corus.client.cli.command.CorusCliCommand.displayProgress(CorusCliCommand.java:167)
	at org.sapia.corus.client.cli.command.Deploy.deployDistribution(Deploy.java:97)
	at org.sapia.corus.client.cli.command.Deploy.doExecute(Deploy.java:67)
	at org.sapia.corus.client.cli.command.CorusCliCommand.execute(CorusCliCommand.java:124)
	at org.sapia.corus.client.cli.CorusCommandFactory$AliasCommand.execute(CorusCommandFactory.java:166)
	at org.sapia.console.CommandConsole.start(CommandConsole.java:115)
	at org.sapia.corus.client.cli.CorusCli.main(CorusCli.java:280)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:190)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:166)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:90)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:281)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:92)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:62)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:254)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:289)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:252)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:191)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:300)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:127)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:716)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:521)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at org.sapia.ubik.rmi.server.transport.http.HttpRmiClientConnection.send(HttpRmiClientConnection.java:91)
	at org.sapia.ubik.rmi.server.invocation.RemoteInvocationStrategy.doDispatchInvocation(RemoteInvocationStrategy.java:78)
	at org.sapia.ubik.rmi.server.invocation.RemoteInvocationStrategy.dispatchInvocation(RemoteInvocationStrategy.java:61)
	at org.sapia.ubik.rmi.server.invocation.InvocationDispatcher.dispatchInvocation(InvocationDispatcher.java:102)
	at org.sapia.ubik.rmi.server.stub.RemoteRefEx.invoke(RemoteRefEx.java:65)
	... 8 more

**Comment by yduchesne** [comment]
Upgrading to httpclient 4.4 fixed this.
