### ISSUE TITLE
Process stays in shutdown mode

### ISSUE THREAD

**Issue by jcdesrochers** [sapia-oss/corus#31]
On corus v 5.0.5

When a system error occur while killing a running process, corus keeps the process in shutdown mode.

```
2016.06.22@11:56:12:919 INFO[org.sapia.corus.taskmanager.CorusTaskManagerImpl]: AttemptKillTask >> Attempting to kill process [Process@c2e24ca:id=1606224096295,pid=53193,status=KILL_REQUESTED,lock=[owner=[id=16,exclusive=true]],deleted=false]. Attempt:
 3; requestor corus.server
2016.06.22@11:56:12:919 ERROR[org.sapia.corus.taskmanager.CorusTaskManagerImpl]: KillTask >> Problem occurred executing task java.lang.reflect.InvocationTargetException
        at org.sapia.corus.taskmanager.core.FutureResult.completed(FutureResult.java:47)
        at org.sapia.corus.taskmanager.core.TaskManagerImpl$2.run(TaskManagerImpl.java:107)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:714)
        at org.sapia.console.CmdLine.exec(CmdLine.java:803)
        at org.sapia.corus.os.UnixProcess.kill(UnixProcess.java:131)
        at org.sapia.corus.os.OsModuleImpl.killProcess(OsModuleImpl.java:79)
        at org.sapia.corus.processor.hook.DefaultProcessKillHook.kill(DefaultProcessKillHook.java:49)
        at org.sapia.corus.processor.hook.ProcessHookManagerImpl.kill(ProcessHookManagerImpl.java:65)
        at org.sapia.corus.processor.task.AttemptKillTask.execute(AttemptKillTask.java:44)
        at org.sapia.corus.processor.task.AttemptKillTask.execute(AttemptKillTask.java:19)
        at org.sapia.corus.taskmanager.core.TaskManagerImpl$2.run(TaskManagerImpl.java:101)
        ... 3 more

2016.06.22@11:56:27:779 INFO[org.sapia.corus.taskmanager.CorusTaskManagerImpl]: ForcefulKillTask >> Process [Process@c2cda6e:id=1606224093791,pid=52449,status=KILL_REQUESTED,lock=[owner=[id=15,exclusive=true]],deleted=false] did not confirm kill; reque
stor: corus.server. Trying to perform a hard kill
2016.06.22@11:56:27:781 INFO[org.sapia.corus.taskmanager.CorusTaskManagerImpl]: ForcefulKillTask >> Error performing OS kill on process [Process@c2cda6e:id=1606224093791,pid=52449,status=KILL_REQUESTED,lock=[owner=[id=15,exclusive=true]],deleted=false]

2016.06.22@11:56:27:781 ERROR[org.sapia.corus.taskmanager.CorusTaskManagerImpl]: ForcefulKillTask >> Error caught java.io.IOException: Cannot run program "kill": error=11, Resource temporarily unavailable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at java.lang.Runtime.exec(Runtime.java:528)
        at org.sapia.console.CmdLineThread.run(CmdLineThread.java:138)
Caused by: java.io.IOException: error=11, Resource temporarily unavailable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 3 more

```

**Comment by yduchesne** [comment]
Fixed in a previous PR
