### ISSUE TITLE
MapDB shutdown hook exception

### ISSUE THREAD

**Issue by jcdesrochers** [sapia-oss/corus#38]
Errors in corus logs upon shutdown.

Corus version: 5.0.5

`Exception in thread "MapDB shutdown hook" [2016-11-28 07:10:51:367] java.lang.NullPointerException
[2016-11-28 07:10:51:367] 	at org.mapdb.Volume$FileChannelVol.sync(Volume.java:1033)
[2016-11-28 07:10:51:367] 	at org.mapdb.StoreWAL.close(StoreWAL.java:1074)
[2016-11-28 07:10:51:367] 	at org.mapdb.EngineWrapper.close(EngineWrapper.java:81)
[2016-11-28 07:10:51:368] 	at org.mapdb.Caches$LRU.close(Caches.java:149)
[2016-11-28 07:10:51:368] 	at org.mapdb.EngineWrapper.close(EngineWrapper.java:81)
[2016-11-28 07:10:51:368] 	at org.mapdb.EngineWrapper$CloseOnJVMShutdown.close(EngineWrapper.java:586)
[2016-11-28 07:10:51:368] 	at org.mapdb.EngineWrapper$CloseOnJVMShutdown$1.run(EngineWrapper.java:571)
[2016-11-28 07:10:51:368] 	at java.lang.Thread.run(Thread.java:745)
`

**Comment by yduchesne** [comment]
Upgraded to latest MapDB version
