### ISSUE TITLE
Undeployment hangs forever

### ISSUE THREAD

**Issue by jcdesrochers** [sapia-oss/corus#51]
On Corus 5.1.5

A 'undeploy -d * -v *' command generated from coruscli hangs forever.

Looking at the threadump we found that:
1) Undeployer triggered a request to the taskmanager to perform an UndeployTask and wait for completion... without any timeout, thus hangs forever.

2) The taskmanager threads are all blocked on other stuff to complete, therefore completing the dead lock preventing any administative operation to take place on this corus node.

Excerp from the threaddump:

**CLIENT REQUEST TO UNDEPLOY DISTRIBUTIONS**
"Ubik.HttpHandler-1": awaiting notification on [0x00000000fbcd1ea0]
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.sapia.corus.taskmanager.core.FutureResult.doGet(FutureResult.java:27)
	at org.sapia.corus.taskmanager.core.FutureResult.get(FutureResult.java:16)
	at org.sapia.corus.deployer.DeployerImpl.undeploy(DeployerImpl.java:403)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sapia.ubik.rmi.server.command.InvokeCommand.execute(InvokeCommand.java:158)
	at org.sapia.corus.client.services.cluster.NonClusteredCommand.execute(NonClusteredCommand.java:77)
	at org.sapia.ubik.rmi.server.transport.CommandHandler.doHandleCommand(CommandHandler.java:74)
	at org.sapia.ubik.rmi.server.transport.CommandHandler.handleCommand(CommandHandler.java:50)
	at org.sapia.ubik.rmi.server.transport.http.UbikHttpHandler.doHandle(UbikHttpHandler.java:66)
	at org.sapia.ubik.rmi.server.transport.http.UbikHttpHandler.access$100(UbikHttpHandler.java:22)
	at org.sapia.ubik.rmi.server.transport.http.UbikHttpHandler$1.run(UbikHttpHandler.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**THREADS OF THE TASKMANAGER BLOCKED ON SOMETHING ELSE**
"ubik.TaskManager-1": awaiting notification on [0x00000000fcde0200]
"ubik.TaskManager-2": awaiting notification on [0x00000000fcde01e8]
"ubik.TaskManager-3": awaiting notification on [0x00000000fcdd61d0]
"ubik.TaskManager-4": awaiting notification on [0x00000000fcdc3ac8]
"ubik.TaskManager-5": awaiting notification on [0x00000000fcdd61b8]
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.sapia.corus.taskmanager.core.FutureResult.doGet(FutureResult.java:27)
	at org.sapia.corus.taskmanager.core.FutureResult.get(FutureResult.java:16)
	at org.sapia.corus.taskmanager.util.CompositeTask.execute(CompositeTask.java:49)
	at org.sapia.corus.taskmanager.util.CompositeTask.execute(CompositeTask.java:17)
	at org.sapia.corus.taskmanager.core.TaskManagerImpl$1.run(TaskManagerImpl.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jcdesrochers** [comment]
Fixed in release 5.1.8
