### ISSUE TITLE
Ubik GC thread seems blocked on socket connection

### ISSUE THREAD

**Issue by jcdesrochers** [sapia-oss/corus#52]
Found this in a threaddump. We have to make sure any socket connection is done in a way that handles connection timeout.

"ubik.rmi.client.GC": running, holding [0x00000000fa981ad0, 0x00000000fa981a48, 0x00000000fa9809d0]
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
	at org.sapia.ubik.rmi.server.transport.http.JdkRmiClientConnection.send(JdkRmiClientConnection.java:83)
	at org.sapia.ubik.rmi.server.transport.http.JdkRmiClientConnection.send(JdkRmiClientConnection.java:141)
	at org.sapia.ubik.rmi.server.gc.ClientGC$HostReference.doSend(ClientGC.java:306)
	at org.sapia.ubik.rmi.server.gc.ClientGC$HostReference.gc(ClientGC.java:287)
	at org.sapia.ubik.rmi.server.gc.ClientGC$HostReferenceTable.gc(ClientGC.java:374)
	at org.sapia.ubik.rmi.server.gc.ClientGC.exec(ClientGC.java:123)
	at org.sapia.ubik.taskman.MultiThreadedTaskManager$1.run(MultiThreadedTaskManager.java:64)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jcdesrochers** [comment]
Worth looking into both setConnectTimeout(...) and setReadTimeout(...)

**Comment by jcdesrochers** [comment]
Fixed and will be available in release 5.1.8
