### ISSUE TITLE
calling exec with profile * generate NPE

### ISSUE THREAD

**Issue by jcdesrochers** [sapia-oss/corus#59]
2017.09.26@12:42:31:496 ERROR[org.sapia.corus.taskmanager.CorusTaskManagerImpl]: ExecTask >> Problem occurred executing task java.lang.reflect.InvocationTargetException
        at org.sapia.corus.taskmanager.core.FutureResult.completed(FutureResult.java:51)
        at org.sapia.corus.taskmanager.core.TaskManagerImpl$3.run(TaskManagerImpl.java:128)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.sapia.corus.client.services.deployer.dist.ProcessConfig.isNumaEnabled(ProcessConfig.java:410)
        at org.sapia.corus.processor.task.PerformExecProcessTask.execute(PerformExecProcessTask.java:126)
        at org.sapia.corus.processor.task.PerformExecProcessTask.execute(PerformExecProcessTask.java:55)
        at org.sapia.corus.taskmanager.core.TaskManagerImpl$3.run(TaskManagerImpl.java:122)
        ... 5 more

**Comment by jcdesrochers** [comment]
Fixed in corus 5.1.10
